#include "transpiler.h"
#include <chrono>
#include <iostream>
#include "ast_visitor.h"

namespace roblox_transpiler {
  Transpiler::Transpiler() : verbose_(false), hasErrors_(false) { index_ = clang_createIndex(0, 0); }

  Transpiler::~Transpiler() {
    if (index_) {
      clang_disposeIndex(index_);
    }
  }

  bool Transpiler::transpileFile(const std::string &inputFile, const std::string &outputFile) {
    std::string luauCode = transpileToString(inputFile);

    if (hasErrors_) {
      return false;
    }

    std::string output = outputFile.empty() ? "tests/output/output.luau" : outputFile;

    LuauCodegen codegen;
    codegen.write(luauCode);
    codegen.writeToFile(output);

    if (verbose_) {
      logInfo("Transpilation completed. Output written to: " + output);
    }

    return true;
  }

  std::string Transpiler::transpileToString(const std::string &inputFile) {
    hasErrors_ = false;
    lastError_.clear();

    auto startTime = std::chrono::high_resolution_clock::now();

    CXTranslationUnit unit;
    if (!parseFile(inputFile, unit)) {
      return "";
    }

    auto rootNode = buildAST(unit, inputFile);
    if (!rootNode) {
      clang_disposeTranslationUnit(unit);
      return "";
    }

    std::string luauCode = generateLuau(rootNode);

    clang_disposeTranslationUnit(unit);

    auto endTime = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime);

    if (verbose_) {
      logInfo("Transpilation completed in " + std::to_string(duration.count()) + "ms");
    }

    return luauCode;
  }

  bool Transpiler::parseFile(const std::string &inputFile, CXTranslationUnit &unit) {
    unit = clang_parseTranslationUnit(index_, inputFile.c_str(), nullptr, 0, nullptr, 0, CXTranslationUnit_None);

    if (!unit) {
      logError("Failed to parse translation unit: " + inputFile);
      return false;
    }

    // Check for parse errors
    unsigned numDiagnostics = clang_getNumDiagnostics(unit);
    bool hasParseErrors = false;

    for (unsigned i = 0; i < numDiagnostics; ++i) {
      CXDiagnostic diagnostic = clang_getDiagnostic(unit, i);
      CXDiagnosticSeverity severity = clang_getDiagnosticSeverity(diagnostic);

      if (severity >= CXDiagnostic_Error) {
        CXString diagStr = clang_formatDiagnostic(diagnostic, clang_defaultDiagnosticDisplayOptions());
        logError("Parse error: " + std::string(clang_getCString(diagStr)));
        clang_disposeString(diagStr);
        hasParseErrors = true;
      }

      clang_disposeDiagnostic(diagnostic);
    }

    if (hasParseErrors) {
      clang_disposeTranslationUnit(unit);
      return false;
    }

    return true;
  }

  std::shared_ptr<LuauNode> Transpiler::buildAST(CXTranslationUnit unit, const std::string &inputFile) {
    auto rootNode = std::make_shared<LuauNode>();
    ASTVisitor visitor(inputFile);
    visitor.setTranslationUnit(unit);
    visitor.setRootNode(rootNode);

    CXCursor rootCursor = clang_getTranslationUnitCursor(unit);

    if (verbose_) {
      logInfo("Starting AST traversal...");
    }

    clang_visitChildren(
        rootCursor,
        [](CXCursor cursor, CXCursor parent, CXClientData clientData) -> CXChildVisitResult {
          auto *visitor = static_cast<ASTVisitor *>(clientData);
          return visitor->visit(cursor, parent);
        },
        &visitor);

    if (verbose_) {
      logInfo("AST traversal completed");
    }

    return visitor.getRootNode();
  }

  std::string Transpiler::generateLuau(std::shared_ptr<LuauNode> rootNode) {
    LuauCodegen codegen;
    codegen.writeComment("Generated by roblox-cpp transpiler");
    codegen.newLine();

    rootNode->render(codegen);

    return codegen.toString();
  }

  bool Transpiler::generateBootstrapper(const std::string &inputFile, const std::string &bootstrapFile) {
    std::string luauCode = transpileToString(inputFile);

    if (hasErrors_) {
      return false;
    }

    LuauCodegen codegen;
    codegen.write(luauCode);
    codegen.writeBootstrapper(bootstrapFile);

    if (verbose_) {
      logInfo("Bootstrapper generated: " + bootstrapFile);
    }

    return true;
  }

  void Transpiler::logError(const std::string &error) {
    hasErrors_ = true;
    lastError_ = error;
    std::cerr << "Error: " << error << std::endl;
  }

  void Transpiler::logInfo(const std::string &info) {
    if (verbose_) {
      std::cout << "Info: " << info << std::endl;
    }
  }
} // namespace roblox_transpiler
